### ISSUE TITLE
Acorn Vulnerabilities

### ISSUE THREAD

**Issue by evilsoft** [articulate/rise-mp3-recorder#12]
It was reported by github that we have numerous dependencies that are victims of the [Acorn Vulnerability][acorn].  Both `eslint` and `babel` need major updates and as such require that the build system be reworked to account for the changes in API.

This package is a dependency in `rise-frontend` and as such will need to be validated and eventually upgraded to the new published version. For validation, this will require a build to be used as a gzip package within `rise-frontend`. This PR could be used to do the final upgrade, once the build is validated and a new version is published to npm.

## Links
* [rise-mp3-recorder][mp3]
* [rise-frontend][frontend]

## Testing
This will have to go through (2) phases of testing:
* Validate the new build in [rise-frontend][frontend].
* Validate the new version in [rise-frontend][frontend] after the package has been published

### Validation
Using a gatekeeper link to the latest build (View Deployment Link):
- [x] Verify that recording works as expected in all locations:
  - [x] Audio Block
  - [x] Media on All Items (Process, Timeline, etc)

[acorn]: https://www.npmjs.com/advisories/1488
[frontend]: https://github.com/articulate/rise-frontend/pull/2339
[mp3]: https://github.com/articulate/rise-mp3-recorder/pull/11/files

**Comment by vicreyes0630** [comment]
Looks good, @evilsoft! let's :shipit: 🚀

**Comment by evilsoft** [comment]
This is out in Prod and 🔴 👁 for final review!
